name: animals
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  onboarding: ^4.0.2
  provider: ^6.1.1
  http: ^1.2.0
  cached_network_image: ^3.3.1
  path_provider: ^2.1.2
  url_launcher: ^6.2.4
  flutter_spinkit: ^5.2.0
  lottie: ^3.0.0
  dio: ^5.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/image/